import type { Metadata } from "next";
import { Monofett, Roboto_Mono } from "next/font/google";
import "./globals.css";

const monofett = Monofett({
  variable: "--font-monofett",
  subsets: ["latin"],
  weight: "400",
});

const geistMono = Roboto_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${monofett.variable} ${geistMono.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
